FROM node:14-alpine

WORKDIR /app

# Copy only the necessary files
COPY package*.json ./
COPY src ./src

# Install dependencies
RUN npm install --production

# Start the application
CMD ["npm", "run", "prod"]
